# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  testProject: 'PrimeService01/PrimeService01.UnitTests'

steps:

- script: dotnet build PrimeService01 --configuration $(buildConfiguration)
  displayName: 'Build Project (Release configuration)'

- script: dotnet test $(testProject) --configuration $(buildConfiguration) --logger trx
  displayName: 'Run Tests (Release configuration)'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish PrimeService01 --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Generate Artifacts for deployment (Release configuration)'
  
- task: PublishBuildArtifacts@1


